---
language: ruby
cache: bundler
addons:
  apt:
    packages:
      - syslog-ng-core
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
install:
  - '[ "${USE_PDK:-1}" == 1 ] && echo gem \"pdk\", \"\~\>1.9.0\">>Gemfile || :'
  - bundle install
  - '[ "${USE_PDK:-1}" == 1 ] && bundle exec pdk build || bundle exec puppet module build'
  - bundle exec puppet module install pkg/*.tar.gz
script:
  - 'bundle exec rake $CHECK'
  - 'bundle exec ./smoke/test -d'
bundler_args: --without system_tests
rvm:
  - 2.3.4
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 4.10" CHECK=parallel_spec USE_PDK=0
      rvm: 2.4.1
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec USE_PDK=1
      rvm: 2.5.3
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec USE_PDK=1
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
