# vim: ft=ruby:noexpandtab

define syslogng::pdb::simple::ruleset (
	$id,
	$patterns,
	$version        = 4,
	$pubdate,
	$description    = "generated by puppet",
	$url            = undef,
	$rules,
) {

	if ! defined(Class['Syslogng::Pdb']) {
		include syslogng::pdb
	}

	validate_array($patterns)
	validate_array($rules)
	validate_string($url)
	validate_string($description)
	validate_string($pub_date)
	validate_re($version, '^\d+$')
	validate_re($pubdate, '^\d+-\d+-\d+$')
	validate_string($provider)
	
	$pdb_file = "${syslogng::pdb::pdb_dir}/${name}.pdb"

	# validate rules
	syslogng_pdb_simple_rule ($rules)
	
	if ! defined(Class['Syslogng::Pdb::Deploy']) {
		include syslogng::pdb::deploy
	}

	file {$pdb_file:
		ensure      => present,
		mode        => 0644,
		content     => template('syslogng/pdb/simple.pdb.erb'),
		notify      => Exec['update-patterndb']
	}
}
