#
define patterndb::simple::ruleset (
  $id,
  $patterns,
  $pubdate,
  $rules,
  $parser = 'default',
  $version        = 4,
# begin currently ignored
  $description    = 'generated by puppet',
  $url            = undef,
# end currently ignored
) {

  if ! defined(Class['Patterndb']) {
    include patterndb
  }

  $patterns_a = string2array($patterns)
  $rules_a = hash2array($rules)
  validate_string($url)
  validate_string($parser)
  validate_string($description)
  validate_string($pubdate)
  validate_re($version, '^\d+$')
  validate_re($pubdate, '^\d+-\d+-\d+$')

  $pdb_file = "${patterndb::pdb_dir}/${parser}/${name}.pdb"

  # validate rules
  patterndb_simple_rule ($rules_a)

  if ! defined(Patterndb::Parser[$parser]) {
    patterndb::parser { $parser: }
  }

  file {$pdb_file:
    ensure      => present,
    mode        => '0644',
    content     => template('patterndb/simple.pdb.erb'),
    notify      => Exec["patterndb::merge::${parser}"]
  }
}
